// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WisMVCApi.Data;

#nullable disable

namespace WisMVCApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WisMVCApi.Models.AnswersModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Yes",
                            DateAndTime = new DateTime(2024, 1, 22, 19, 45, 2, 999, DateTimeKind.Utc).AddTicks(903),
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Answer = "4",
                            DateAndTime = new DateTime(2024, 1, 22, 19, 45, 2, 999, DateTimeKind.Utc).AddTicks(905),
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Answer = "2",
                            DateAndTime = new DateTime(2024, 1, 22, 19, 45, 2, 999, DateTimeKind.Utc).AddTicks(905),
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 4,
                            Answer = "5",
                            DateAndTime = new DateTime(2024, 1, 22, 19, 45, 2, 999, DateTimeKind.Utc).AddTicks(906),
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 5,
                            Answer = "It's ok, i guess.",
                            DateAndTime = new DateTime(2024, 1, 22, 19, 45, 2, 999, DateTimeKind.Utc).AddTicks(906),
                            QuestionId = 5
                        });
                });

            modelBuilder.Entity("WisMVCApi.Models.QuestionsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AnswerType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnswerType = "options",
                            Text = "Yes / No / Don’t know what a cyborg is",
                            Title = "Are we cyborgs?"
                        },
                        new
                        {
                            Id = 2,
                            AnswerType = "number",
                            Text = "1-5",
                            Title = "Do technology set us free?"
                        },
                        new
                        {
                            Id = 3,
                            AnswerType = "number",
                            Text = "1-5",
                            Title = "Are you worried about the future?"
                        },
                        new
                        {
                            Id = 4,
                            AnswerType = "number",
                            Text = "1-5",
                            Title = "Does our job define us?"
                        },
                        new
                        {
                            Id = 5,
                            AnswerType = "text",
                            Text = "You can write anything",
                            Title = "How would you describe your mental health?"
                        });
                });

            modelBuilder.Entity("WisMVCApi.Models.AnswersModel", b =>
                {
                    b.HasOne("WisMVCApi.Models.QuestionsModel", "Questions")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("WisMVCApi.Models.QuestionsModel", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
