// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WisMVCApi.Data;

#nullable disable

namespace WisMVCApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WisMVCApi.Models.AnswersModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = 5,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Number = 4,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Number = 2,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 4,
                            Number = 5,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 5,
                            Number = 5,
                            QuestionId = 5
                        });
                });

            modelBuilder.Entity("WisMVCApi.Models.QuestionsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "Yes / No/Don’t know what a cyborg is",
                            Title = "Are we cyborgs?"
                        },
                        new
                        {
                            Id = 2,
                            Text = "1-5",
                            Title = "Do technology set us free?"
                        },
                        new
                        {
                            Id = 3,
                            Text = "1-5",
                            Title = "Are you worried about the future?"
                        },
                        new
                        {
                            Id = 4,
                            Text = "1-5",
                            Title = "Does our job define us?"
                        },
                        new
                        {
                            Id = 5,
                            Text = "1-5",
                            Title = "How would you describe your mental health?"
                        });
                });

            modelBuilder.Entity("WisMVCApi.Models.AnswersModel", b =>
                {
                    b.HasOne("WisMVCApi.Models.QuestionsModel", "Questions")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("WisMVCApi.Models.QuestionsModel", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
